name: CR

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

on:
  pull_request:
    branches: [mscpo]
    types: [opened, synchronize, labeled, ready_for_review]
    paths-ignore:
      - '.github/**'
      - '__tests__/**'
      - 'art/**'
      - 'docs/**'
      - '*.md'
  push:
    branches: [mscpo]
    paths-ignore:
      - '__tests__/**'
      - 'art/**'
      - 'docs/**'
      - '*.md'
    tags-ignore:
      - '*'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
