name: CR

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

on:
  pull_request:
    branches: [mscpo]
    types: [opened, synchronize, labeled, ready_for_review]
    paths-ignore:
      - '.github/**'
      - '__tests__/**'
      - 'art/**'
      - 'docs/**'
      - '*.md'
  push:
    branches: [mscpo]
    paths-ignore:
      - '__tests__/**'
      - 'art/**'
      - 'docs/**'
      - '*.md'
    tags-ignore:
      - '*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  release:
    if: ${{ ((github.event_name == 'pull_request' && !github.event.pull_request.draft && contains(github.event.pull_request.labels.*.name, 'cr-tracked') && !contains(github.event.pull_request.labels.*.name, 'spam') && !contains(github.event.pull_request.labels.*.name, 'invalid')) || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'release:'))) && github.repository == 'vuejs/vitepress' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated Build
          branch: artifact
          file_pattern: 'bin/ dist/ types/ template/ lib/ client.d.ts theme.d.ts theme-without-fonts.d.ts'
          commit_user_name: Automated Build Bot # defaults to "github-actions[bot]"
          commit_author: Automated Build Bot <actions@github.com>
